FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    clang \
    cmake \
    git \
    gdb \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
